services:
  gatsby:
    build: ./
    container_name: gatsby
    tty: true
    stdin_open: true
    volumes:
      - .:/gatsby
    environment:
      - NODE_ENV=development
    ports:
      - 8000:8000
