services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: popolog
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    stdin_open: true
    environment:
      - NODE_ENV=development